---
title: "Observations of fatal shootings in the US from 2015-2022"
output: 
  flexdashboard::flex_dashboard:
   orientation: rows
   #vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
#library(flexdashboard)
library(shiny)
library(ggplot2)
library(dplyr)
library(readr)
library(flexdashboard)
library(ECharts2Shiny)
library(plotly)
library(DT)
library(shinyWidgets)
#install.packages(ECharts2Shiny)
#install.packages('ggguitar')

#install.packages("shinyWidgets")

dataset <- read_csv("US Police shootings in from 2015-22_alt_race.csv")

```



Row
------------------------
### Value Boxes 
```{r}

#Need to drop the na from age (Value Box 1 )
dataset <- dataset %>% filter(!is.na(age))

# Calculate the average age across all races (Gauge 1)
avg_age <- mean(dataset$age)


averageAge <- reactive({
  filtered_data <- dataset %>%
    filter(race %in% input$race)
  filtered_data %>% summarise(avg_age = mean(age))
})
output$ageBox <- renderValueBox({
  valueBox(paste("Average age at time of death: ", round(averageAge()$avg_age, 2)), color = "blue")
})

# Start of valueBox Armed 

dataset_armed <- dataset %>%
  mutate(armed = ifelse(is.na(armed),0,ifelse(armed == "Yes",1,0))) %>%
  na.omit()

sum_armed_by_race <- dataset_armed %>%
  group_by(race) %>%
  summarize(sum_armed = sum(armed))

filtered_data_a <- reactive({
  dataset_armed %>%
    filter(race == input$filter_variable)
})

output$armedBox <- renderValueBox({
  valueBox(paste("Sum of armed people by race: ", sum(filtered_data_a()$armed)), color = "blue")
})


#Start of the valueBox state

output$stateBox <- renderValueBox({
  filtered_data <- data_subset() %>%
    filter(
      !is.na(age)
    ) %>%
    mutate(armed = ifelse(is.na(armed),0,ifelse(armed == "Yes",1,0)))
  
  total_deaths <- filtered_data %>% 
                  summarise(total_deaths = n()) %>% 
                  pull(total_deaths)
  valueBox(paste("Total Deaths in Selected States: ", total_deaths), color = "blue")
})


fluidRow(
  column(width = 4,
    fluidRow(valueBoxOutput("ageBox"))
  ),
  column(width = 4,
    fluidRow(valueBoxOutput("armedBox"))
  ),
  column(width = 4, 
    fluidRow(valueBoxOutput("stateBox"))
 )
)

# I had to literally fight for my life to get this to work, I was hoping to have them each in their own "button" but ran out of time.
```

Row {.tabset .tabset-fade}
-------------------------

### Age distribution based on race  

```{r}
# Whisker Plot Highlighting mean age based off select-able race

#Creating the check box input for the races
checkboxGroupInput("race", "Race", choices = c("Asian","Black", "Hispanic", "Non-His / Lat", "Other", "Pacific Islander", "White"),

                    selected = c("Asian","Black", "Hispanic", "Non-His / Lat", "Other", "Pacific Islander", "White"), inline = TRUE)


#Creating the reactive whisker plot 
whiskerPlot <- reactive({
  filtered_data <- dataset %>%
    filter(race %in% input$race)
  ggplot(filtered_data, aes(x = race, y = age, color = factor(race))) +
    geom_boxplot()
})

#Output for the whiskerplot to plotly 
output$whiskerPlot <- renderPlotly({
  ggplotly(whiskerPlot())
    
})

plotlyOutput("whiskerPlot", width = "100%", height = 500)


# I am not sure if there is a better or more efficient was to do this but I was able to Frankenstein this together and it works. 
```

-----------------------

### Armed during incident 
```{r}
# mutating the various categories of "armed" to 1 and 0
dataset_armed <- dataset %>%
  mutate(armed = ifelse(is.na(armed), 0, ifelse(armed == "Yes", 1, 0))) %>%
  na.omit()

#Getting the sum of shootings by race 
sum_armed_by_race <- dataset_armed %>%
  group_by(race) %>%
  summarize(sum_armed = sum(armed))


selectInput("filter_variable", "Filter by:",
            choices = c("Asian","Black", "Hispanic", "Non-His / Lat", "Other", "Pacific Islander", "White"),
            selected = c("Asian","Black", "Hispanic", "Non-His / Lat", "Other", "Pacific Islander", "White"),
            multiple = TRUE)


output$plot <- renderPlotly({
  filtered_data_a <- dataset_armed %>%
    filter(race %in% input$filter_variable)
  
  plot_ly(data = filtered_data_a, x = ~race, y = ~armed, type = "bar",
          marker = list(color = "red")) %>%
    layout(yaxis = list(title = "Number of Armed People"),
           title = paste("Number of Armed People by Race:", paste(input$filter_variable, collapse = ",")))
})

plotlyOutput("plot", width = 800, height = 600)

```

### Shootings per state  
```{r}

data_subset <- reactive({
  dataset %>%
    filter(
      state %in% input$state
    )
})
selectInput("state", "Select State(s):",
            choices = sort(unique(dataset$state)),
            selected = c("PA","WV","OH"),
            multiple = TRUE)

renderPlotly({
  filtered_data <- data_subset()
  total_deaths_per_state <- filtered_data %>%
    group_by(state) %>%
    summarise(total_deaths = n())

  plot_ly(total_deaths_per_state, x = ~state, y = ~total_deaths, type = 'bar', color = ~state)
})


```

### Data Table 
```{r}
# Create the data table
data_table <- datatable(dataset, options = list(pageLength = 25))

# Render the data table
renderDT(data_table)
```
